In [2]:
#Write a Python program to convert an array to an ordinary list with the same items.We can use the np.tolist() function

import numpy

arr1=numpy.array([5,6,7])
list1=arr1.tolist()
print(list1)

[5, 6, 7]


In [14]:
#Write a NumPy program to compute the sum of the diagonal elements of a given array.
import numpy as np
arr= np.arange(9).reshape(3,3)
print(arr)
np.diagonal(arr)
print ("the sum of the diagonal array", np.diagonal(arr), "is",sum(np.diagonal(arr)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
the sum of the diagonal array [0 4 8] is 12


In [19]:
#Given an array of your choice, get all the values higher than X:
#If a = [[1,2],[3,5]] and x = 2 :  then 3 and 5 are higher than 2. 
import numpy as np

arr3=np.array[[1,2],[3,5]]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [22]:
#Given two arrays, A & B have the same shape. 
#The task is to apply addition by hand: C is the new array

import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
print (c)

[5 7 9]


In [25]:
#Write a NumPy program to subtract the mean of each row of a given matrix.
#Hint: use the mean function
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
print (np.mean(c))

7.0
